var quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "It does not matter how slowly you go, as long as you do not stop. - Confucius",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "Every strike brings me closer to the next home run. - Babe Ruth",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "Life is what happens when you're busy making other plans. - Allen Sanders",
  "I've failed over and over and over again in my life and that is why I've been successful. - Michael Jordan",
  "Don't cry because it's over, smile because it happened. - Dr. Seuss",
  "Be yourself; everyone else is already taken. - Oscar Wilde",
  "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
  "Be the change that you wish to see in the world. - Mahatma Gandhi",
  "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
  "The only impossible journey is the one you never begin. - Tony Robbins",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "The best way to predict the future is to create it. - Peter Drucker",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Whatever you are, be a good one. - Abraham Lincoln",
  "It is never too late to be what you might have been. - George Eliot",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Life is really simple, but we insist on making it complicated. - Confucius",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
  "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
  "There is only one happiness in this life, to love and be loved. - George Sand",
  "You miss 100% of the shots you don't take. - Wayne Gretzky",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
  "Strive not to be a success, but rather to be of value. - Albert Einstein",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Get busy living or get busy dying. - Stephen King",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
];

function newQuote() {
  var randomNumber = Math.floor(Math.random() * quotes.length);
  document.getElementById("quote").innerHTML = quotes[randomNumber];
}
